[package]
name = "la_nids"
version = "0.1.0"
authors = ["James Stow <jamesstow2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.7"
rayon = "1.5.0"

wgpu = "0.6.0"
bytemuck = "1.4.1"